version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_PASSWORD: sekret
      VIRTUAL_HOST: express.docker
      VIRTUAL_PORT: $PORT
      PORT: $PORT
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: sekret
    volumes:
      - db-data:/usr/local/pgsql/data
volumes:
  db-data: {}
